server:
  port: 8060

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8080"
  cloud:
    gateway:
      mvc:
        routes:
          - id: student-service
            uri: http://localhost:8080
            predicates:
              - Path=/student-service/**
          - id: address-service
            uri: http://localhost:8081
            predicates:
              - Path=/address-service/**





